export const SPLASH = "Splash"
export const WELCOME = "Welcome"
export const LOGIN = "Login"
export const SIGN_UP = "SignUp"
export const FORGOT_PASSWORD = "ForgotPassword"
export const MESSAGES = "Messages"
export const PROFILE_USER = "ProfileUser"
export const FRIENDS = "Friends"
